{% set package_name = "elog" %}
{% set import_name = "elog" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv



requirements:
  build:
  - python >=3.5
  - setuptools_scm
  - pip
  run:
  - python >=3.5
  - requests
  - krtc
  - ophyd



test:
  imports:
  - elog



about:
  home: https://github.com/pcdshub/elog
  license: SLAC Open License
  summary: Python API for interfacing with LCLS ELog
